<?php

class SetDesignTableSeeder extends Seeder {

	public function run()
	{
		// Uncomment the below to wipe the table clean before populating
		DB::table('setdesign')->delete();

		$array = array(
			array(
					'slug' => 'Interview-Magazine-Bill-Hader',
					'name' => 'Interview Magazine Bill Hader',
					'client' => 'Interview Magazine',
					'client_url' => 'http://www.interviewmagazine.com/',
					'director' => '',
					'director_url' => '',
					'photographer' => 'Jai Odell',
					'photographer_url' => '',
					'stylist' => 'Michelle Cameron',
					'stylist_url' => 'http://www.frankreps.com/stylists/michelle-cameron/print#/stylists/michelle-cameron/print/50351f45-4ea8-4f58-bf1e-70810a0b0910',
					'talent' => 'Bill Hader',
					'talent_agency' => '',
					'talent_url' => 'http://www.imdb.com/name/nm0352778/',
					'makeup' => 'Susie Sobol',
					'makeup_url' => 'http://www.susiesobol.com/',
					'hair' => 'Joey George',
					'hair_url' => 'http://joeygeorge.4ormat.com/',
					'photocover_id' => null
			)
			,
			array(
					'slug' => 'Club-Monaco-September',
					'name' => 'Club Monaco September',
					'client' => 'Club Monaco',
					'client_url' => 'http://www.clubmonaco.com/',
					'director' => '',
					'director_url' => '',
					'photographer' => 'Jai Odell',
					'photographer_url' => 'http://jaiodell.com/',
					'stylist' => 'Aleksandra Woroneicka',
					'stylist_url' => 'http://www.managementartists.com/stylists/aleksandra-woroniecka',
					'talent' => 'Luca Gadjus',
					'talent_agency' => '',
					'talent_url' => 'http://models.com/models/luca-gadjus  ',
					'makeup' => 'Morgane Martini',
					'makeup_url' => 'http://www.artlistparis.com/make-up/morgane-martini',
					'hair' => 'Shin Arima',
					'hair_url' => 'http://www.frankreps.com/hair/shin-arima/print#/hair/shin-arima/print/51892bff-84f0-4f3e-8267-472a0aa613db',
					'photocover_id' => null
			),
			array(
					'slug' => 'Vogue-Australia',
					'name' => 'Vogue Australia',
					'client' => 'Vogue Australia',
					'client_url' => 'http://www.vogue.com.au/',
					'director' => '',
					'director_url' => '',
					'photographer' => 'Jai Odell',
					'photographer_url' => 'http://jaiodell.com/',
					'stylist' => 'Jessica dos Remedios',
					'stylist_url' => 'http://jessicadosremedios.com/',
					'talent' => 'Elisaveta + Vera',
					'talent_agency' => 'Parts Models LLC',
					'talent_url' => '',
					'makeup' => 'Susie Sobol',
					'makeup_url' => 'http://www.susiesobol.com/',
					'hair' => '',
					'hair_url' => '',
					'photocover_id' => null
			),
			array(
					'slug' => 'Kim-Haller',
					'name' => 'Kim Haller',
					'client' => 'Kim Haller Collection',
					'client_url' => 'http://www.kim-haller.com',
					'director' => '',
					'director_url' => '',
					'photographer' => 'Paolo Ambrosi de Magistris + Murray Hall',
					'photographer_url' => 'http://www.pamu.com/',
					'stylist' => 'Angelica Nelson',
					'stylist_url' => 'http://www.inartistmanagement.com/STYLIST/ANGELICA--Nelson/1/',
					'talent' => '',
					'talent_agency' => '',
					'talent_url' => '',
					'makeup' => 'Yinna Wang',
					'makeup_url' => 'http://www.dripbook.com/yinnawang/',
					'hair' => 'Tony Kelley',
					'hair_url' => 'http://www.tonykelleyhair.com/',
					'photocover_id' => null
			),
			array(
					'slug' => 'i-D-Magazine-Editorial',
					'name' => 'i-D Magazine Editorial',
					'client' => 'i-D Magazine',
					'client_url' => 'http://i-d.vice.com/en_gb/',
					'director' => '',
					'director_url' => '',
			 		'photographer' => 'Jai Odell',
			 		'photographer_url' => 'http://www.jaiodell.com',
			 		'stylist' => 'Katelyn Gray',
			 		'stylist_url' => 'http://instagram.com/katelynjgray',
			 		'talent' => 'Kremi',
			 		'talent_agency' => 'Supreme',
			 		'talent_url' => 'http://www.suprememanagement.com/Models/2512/KREMI',
			 		'makeup' => 'Kanako Takase',
			 		'makeup_url' => 'http://models.com/people/kanako-takase',
			 		'hair' => 'Ryan Mitchell',
			 		'hair_url' => '',
			 		'photocover_id' => null
			 ),
			 array(
			 		'slug' => 'Jake-Jones-Test',
			 		'name' => 'Jake Jones Test',
			 		'client' => '',
			 		'client_url' => '',
					'director' => '',
					'director_url' => '',
			 		'photographer' => 'Jake Jones',
			 		'photographer_url' => 'http://www.whoisjakejones.com/',
			 		'stylist' => 'Yoshihiro Hidaka',
			 		'stylist_url' => 'http://www.yoshihirohidaka.com/',
			 		'talent' => 'Vanessa Moody',
			 		'talent_agency' => '',
			 		'talent_url' => 'http://models.com/models/vanessa-moody',
			 		'makeup' => 'Akiko Owada',
			 		'makeup_url' => 'http://akikoowada.com/',
			 		'hair' => 'Neil Grupp',
			 		'hair_url' => 'http://neilgrupp.com/',
			 		'photocover_id' => null
			 ),
			 array(
			 		'slug' => 'i-D-Magazine-Andre-Walker',
			 		'name' => 'i-D Magazine Andre Walker',
			 		'client' => 'i-D Magazine',
			 		'client_url' => 'http://i-d.vice.com/en_gb/',
					'director' => '',
					'director_url' => '',
			 		'photographer' => 'Jai Odell',
			 		'photographer_url' => 'http://jaiodell.com',
			 		'stylist' => 'Stella Greenspan',
			 		'stylist_url' => 'http://models.com/people/stella-greenspan',
			 		'talent' => 'Manuela Frey',
			 		'talent_agency' => '',
			 		'talent_url' => 'http://models.com/models/manuela-frey',
			 		'makeup' => 'Marla Belt',
			 		'makeup_url' => 'http://www.streeters.com/artists/makeup-artists/marla-belt/portfolio',
			 		'hair' => 'Kayla MiChele',
			 		'hair_url' => 'http://kaylamichele.com/',
			 		'photocover_id' => null
			 ),
			 array(
			 		'slug' => 'The-Last-Magazine-Noir',
			 		'name' => 'The Last Magazine Noir',
			 		'client' => 'The Last Magazine',
			 		'client_url' => 'http://thelast-magazine.com/',
					'director' => '',
					'director_url' => '',
			 		'photographer' => 'Jai Odell',
			 		'photographer_url' => 'http://jaiodell.com/',
			 		'stylist' => 'Zara Zachrisson',
			 		'stylist_url' => 'http://cargocollective.com/zarazachrisson',
			 		'talent' => 'Naty Chabanenko',
			 		'talent_agency' => '',
			 		'talent_url' => 'http://models.com/models/Naty-Chabanenko',
			 		'makeup' => 'Susie Sobol',
			 		'makeup_url' => 'http://www.susiesobol.com/',
			 		'hair' => 'Kayla MiChele',
			 		'hair_url' => 'http://kaylamichele.com/',
			 		'photocover_id' => null
			 ),
			 array(
			 		'slug' => 'Society',
			 		'name' => 'Society',
			 		'client' => 'Society',
			 		'client_url' => '',
					'director' => '',
					'director_url' => '',
			 		'photographer' => 'Jai Odell',
			 		'photographer_url' => 'http://jaiodell.com/',
			 		'stylist' => 'Sasha Kelly',
			 		'stylist_url' => 'http://www.sasha-kelly.com/',
			 		'talent' => 'Pamela Bernier',
			 		'talent_agency' => '',
			 		'talent_url' => 'http://models.com/models/pamela-bernier',
			 		'makeup' => 'Georgi Sandev',
			 		'makeup_url' => 'http://www.georgisandev.com/index2.php#/home/',
			 		'hair' => 'Shingo Shibata',
			 		'hair_url' => 'http://models.com/people/shingo-shibata',
			 		'photocover_id' => null
			 ),
			 array(
			 		'slug' => 'Marfa-Journal',
			 		'name' => 'Marfa Journal',
			 		'client' => 'Marfa Journal',
			 		'client_url' => 'http://marfajournal.com/',
					'director' => '',
					'director_url' => '',
			 		'photographer' => 'Jai Odell',
			 		'photographer_url' => 'http://jaiodell.com/',
			 		'stylist' => 'Britt Berger',
			 		'stylist_url' => 'http://www.brittberger.com/',
			 		'talent' => 'Kelly Mittendorf',
			 		'talent_agency' => '',
			 		'talent_url' => 'http://models.com/models/kelly-mittendorf',
			 		'makeup' => 'Georgie Sandev',
			 		'makeup_url' => 'http://www.georgisandev.com/index2.php#/home/',
			 		'hair' => 'Kayla Michele',
			 		'hair_url' => 'http://kaylamichele.com/',
			 		'photocover_id' => null
			 ),
			 array(
			 		'slug' => 'Seedless',
			 		'name' => 'Seedless',
			 		'client' => '',
			 		'client_url' => '',
					'director' => '',
					'director_url' => '',
			 		'photographer' => 'Brendan Burdzinsky  ',
			 		'photographer_url' => 'http://www.brendanburdzinski.com/',
			 		'stylist' => '',
			 		'stylist_url' => '',
			 		'talent' => '',
			 		'talent_agency' => '',
			 		'talent_url' => '',
			 		'makeup' => '',
			 		'makeup_url' => '',
			 		'hair' => '',
			 		'hair_url' => '',
			 		'photocover_id' => null
			 ),
			 array(
			 		'slug' => 'Jonathan-Cohen-SS-2014',
			 		'name' => 'Jonathan Cohen SS 2014',
			 		'client' => 'Jonathan Cohen Studio',
			 		'client_url' => 'http://jonathancohenstudio.com/',
					'director' => '',
					'director_url' => '',
			 		'photographer' => 'Spencer Ostrander',
			 		'photographer_url' => '',
			 		'stylist' => 'Woldy Reyes',
			 		'stylist_url' => '',
			 		'talent' => 'Carolina Sjostrand',
			 		'talent_agency' => 'http://models.com/models/carolina-sjostrand',
			 		'talent_url' => '',
			 		'makeup' => 'Angelica Perri',
			 		'makeup_url' => '',
			 		'hair' => 'Stephanie',
			 		'hair_url' => 'http://www.shuuemura-usa.com/',
			 		'photocover_id' => null
			 ),
			 array(
			 		'slug' => 'Mens-World',
			 		'name' => 'Mens World',
			 		'client' => '',
			 		'client_url' => '',
					'director' => '',
					'director_url' => '',
			 		'photographer' => 'Alex Waltl ',
			 		'photographer_url' => '',
			 		'stylist' => 'Edward Lorenz',
			 		'stylist_url' => '',
			 		'talent' => 'Naleye Dolmans',
			 		'talent_agency' => '',
			 		'talent_url' => '',
			 		'makeup' => '',
			 		'makeup_url' => '',
			 		'hair' => 'Shane Thomas',
			 		'hair_url' => 'http://www.shanethomashair.com/',
			 		'photocover_id' => null
			 ),
			 array(
			 		'slug' => 'Wolf-Magazine',
			 		'name' => 'Wolf Magazine',
			 		'client' => 'Wolf Magazine',
			 		'client_url' => 'http://wolfmagazine.com/',
			 		'photographer' => 'Adam Franzino',
			 		'photographer_url' => 'http://www.adamfranzino.com',
					 'director' => 'Trevor Owsley',
					 'director_url' => 'http://www.trevorowsley.com',
			 		'stylist' => '',
			 		'stylist_url' => '',
			 		'talent' => 'Nadia Lacka',
			 		'talent_agency' => '',
			 		'talent_url' => 'http://www.mc2models.com/new-york/main-board/nadia',
			 		'makeup' => 'Tracey Alfajora',
			 		'makeup_url' => 'http://art-dept.com/makeup/tracy-alfajora/editorial-i',
			 		'hair' => 'Shane Thomas',
			 		'hair_url' => 'http://www.shanethomas.com/',
			 		'photocover_id' => null
			 ),
			 array(
			 		'slug' => 'Urban-Zen-Finals',
			 		'name' => 'Urban Zen Finals',
			 		'client' => 'Urban Zen',
			 		'client_url' => 'http://www.urbanzen.com/',
					'director' => '',
					'director_url' => '',
			 		'photographer' => 'Adam Franzino',
			 		'photographer_url' => 'http://www.adamfranzino.com/',
			 		'stylist' => 'Lisa Keshtkar',
			 		'stylist_url' => 'http://www.linkedin.com/pub/lisa-keshtkar/11/227/9a9',
			 		'talent' => 'Ieva and Aida Aniulyte',
			 		'talent_agency' => '',
			 		'talent_url' => '',
			 		'makeup' => 'Tracey Alfajora',
			 		'makeup_url' => 'http://art-dept.com/makeup/tracy-alfajora/editorial-i',
			 		'hair' => 'Martin Christopher Harper',
			 		'hair_url' => 'http://martin-christopherharper.com/',
			 		'photocover_id' => null
			 )
		);

		
		DB::table('setdesign')->insert($array);
	}

}