<?php

class SetDesignTableSeeder extends Seeder {

	public function run()
	{
		// Uncomment the below to wipe the table clean before populating
		DB::table('setdesign')->delete();

		$array = array(
			array(
					'slug' => 'Urban-Zen',
					'name' => 'Urban Zen',
					'client' => 'Urban Zen',
					'client_url' => 'http://www.urbanzen.com/',
					'director' => '',
					'director_url' => '',
					'photographer' => 'Adam Franzino',
					'photographer_url' => 'http://www.adamfranzino.com/',
					'stylist' => 'Lisa Keshtkar',
					'stylist_url' => 'http://www.linkedin.com/pub/lisa-keshtkar/11/227/9a9',
					'talent' => 'Ieva and Aida Aniulyte',
					'talent_agency' => '',
					'talent_url' => '',
					'makeup' => 'Tracey Alfajora',
					'makeup_url' => 'http://art-dept.com/makeup/tracy-alfajora/editorial-i',
					'hair' => 'Martin Christopher Harper',
					'hair_url' => 'http://martin-christopherharper.com/',
					'cover_photo' => 'images/01Urban_Zen_Finals/urbanzen-01.jpg'
			),
			array(
					'slug' => 'Wolf-Magazine',
					'name' => 'Wolf Magazine',
					'client' => 'Wolf Magazine',
					'client_url' => 'http://wolfmagazine.com/',
					'photographer' => 'Adam Franzino',
					'photographer_url' => 'http://www.adamfranzino.com',
					'director' => 'Trevor Owsley',
					'director_url' => 'http://www.trevorowsley.com',
					'stylist' => '',
					'stylist_url' => '',
					'talent' => 'Nadia Lacka',
					'talent_agency' => '',
					'talent_url' => 'http://www.mc2models.com/new-york/main-board/nadia',
					'makeup' => 'Tracey Alfajora',
					'makeup_url' => 'http://art-dept.com/makeup/tracy-alfajora/editorial-i',
					'hair' => 'Shane Thomas',
					'hair_url' => 'http://www.shanethomas.com/',
					'cover_photo' => 'images/02Wolf_Magazine/wolfmagazine-thumbnail.jpg'
			),
			array(
					'slug' => 'Mens-World',
					'name' => 'Mens World',
					'client' => '',
					'client_url' => '',
					'director' => '',
					'director_url' => '',
					'photographer' => 'Alex Waltl ',
					'photographer_url' => '',
					'stylist' => 'Edward Lorenz',
					'stylist_url' => '',
					'talent' => 'Naleye Dolmans',
					'talent_agency' => '',
					'talent_url' => '',
					'makeup' => '',
					'makeup_url' => '',
					'hair' => 'Shane Thomas',
					'hair_url' => 'http://www.shanethomashair.com/',
					'cover_photo' => 'images/03Mens_World_Web/Mens-World-01.jpg'
			),
			array(
					'slug' => 'Jonathan-Cohen-SS-2014',
					'name' => 'Jonathan Cohen SS 2014',
					'client' => 'Jonathan Cohen Studio',
					'client_url' => 'http://jonathancohenstudio.com/',
					'director' => '',
					'director_url' => '',
					'photographer' => 'Spencer Ostrander',
					'photographer_url' => '',
					'stylist' => 'Woldy Reyes',
					'stylist_url' => '',
					'talent' => 'Carolina Sjostrand',
					'talent_agency' => 'http://models.com/models/carolina-sjostrand',
					'talent_url' => '',
					'makeup' => 'Angelica Perri',
					'makeup_url' => '',
					'hair' => 'Stephanie',
					'hair_url' => 'http://www.shuuemura-usa.com/',
					'cover_photo' => 'images/04Jonathan_Cohen_SS_2014/jonathancohen-01.jpg'
			),
			array(
					'slug' => 'Seedless',
					'name' => 'Seedless',
					'client' => '',
					'client_url' => '',
					'director' => '',
					'director_url' => '',
					'photographer' => 'Brendan Burdzinsky  ',
					'photographer_url' => 'http://www.brendanburdzinski.com/',
					'stylist' => '',
					'stylist_url' => '',
					'talent' => '',
					'talent_agency' => '',
					'talent_url' => '',
					'makeup' => '',
					'makeup_url' => '',
					'hair' => '',
					'hair_url' => '',
					'cover_photo' => 'images/05Seedless/seedless-thumbnail.jpg'
			),
			array(
					'slug' => 'Marfa-Journal',
					'name' => 'Marfa Journal',
					'client' => 'Marfa Journal',
					'client_url' => 'http://marfajournal.com/',
					'director' => '',
					'director_url' => '',
					'photographer' => 'Jai Odell',
					'photographer_url' => 'http://www.jaiodell.com',
					'stylist' => 'Britt Berger',
					'stylist_url' => 'http://www.brittberger.com/',
					'talent' => 'Kelly Mittendorf',
					'talent_agency' => '',
					'talent_url' => 'http://models.com/models/kelly-mittendorf',
					'makeup' => 'Georgie Sandev',
					'makeup_url' => 'http://www.georgisandev.com/index2.php#/home/',
					'hair' => 'Kayla Michele',
					'hair_url' => 'http://kaylamichele.com/',
					'cover_photo' => 'images/06Marfa_Journal/marfa-02.jpg'
			),
			array(
					'slug' => 'Society',
					'name' => 'Society',
					'client' => 'Society',
					'client_url' => '',
					'director' => '',
					'director_url' => '',
					'photographer' => 'Jai Odell',
					'photographer_url' => 'http://www.jaiodell.com',
					'stylist' => 'Sasha Kelly',
					'stylist_url' => 'http://www.sasha-kelly.com/',
					'talent' => 'Pamela Bernier',
					'talent_agency' => '',
					'talent_url' => 'http://models.com/models/pamela-bernier',
					'makeup' => 'Georgi Sandev',
					'makeup_url' => 'http://www.georgisandev.com/index2.php#/home/',
					'hair' => 'Shingo Shibata',
					'hair_url' => 'http://models.com/people/shingo-shibata',
					'cover_photo' => 'images/07Society/society-01.jpg'
			),
			array(
					'slug' => 'The-Last-Magazine',
					'name' => 'The Last Magazine',
					'client' => 'The Last Magazine',
					'client_url' => 'http://thelast-magazine.com/',
					'director' => '',
					'director_url' => '',
					'photographer' => 'Jai Odell',
					'photographer_url' => 'http://www.jaiodell.com',
					'stylist' => 'Zara Zachrisson',
					'stylist_url' => 'http://cargocollective.com/zarazachrisson',
					'talent' => 'Naty Chabanenko',
					'talent_agency' => '',
					'talent_url' => 'http://models.com/models/Naty-Chabanenko',
					'makeup' => 'Susie Sobol',
					'makeup_url' => 'http://www.susiesobol.com/',
					'hair' => 'Kayla MiChele',
					'hair_url' => 'http://kaylamichele.com/',
					'cover_photo' => 'images/08The_Last_Magazine_Noir/lastmagazinenoir-08.jpg'
			),
			array(
					'slug' => 'i-D-Magazine-1',
					'name' => 'i-D Magazine',
					'client' => 'i-D Magazine',
					'client_url' => 'http://i-d.vice.com/en_gb/',
					'director' => '',
					'director_url' => '',
					'photographer' => 'Jai Odell',
					'photographer_url' => 'http://jaiodell.com',
					'stylist' => 'Stella Greenspan',
					'stylist_url' => 'http://models.com/people/stella-greenspan',
					'talent' => 'Manuela Frey',
					'talent_agency' => '',
					'talent_url' => 'http://models.com/models/manuela-frey',
					'makeup' => 'Marla Belt',
					'makeup_url' => 'http://www.streeters.com/artists/makeup-artists/marla-belt/portfolio',
					'hair' => 'Kayla MiChele',
					'hair_url' => 'http://kaylamichele.com/',
					'cover_photo' => 'images/09i-D_Magazine_Andre_Walker/id-01.jpg'
			),
			array(
					'slug' => 'Jake-Jones',
					'name' => 'Jake Jones',
					'client' => '',
					'client_url' => '',
					'director' => '',
					'director_url' => '',
					'photographer' => 'Jake Jones',
					'photographer_url' => 'http://www.whoisjakejones.com/',
					'stylist' => 'Yoshihiro Hidaka',
					'stylist_url' => 'http://www.yoshihirohidaka.com/',
					'talent' => 'Vanessa Moody',
					'talent_agency' => '',
					'talent_url' => 'http://models.com/models/vanessa-moody',
					'makeup' => 'Akiko Owada',
					'makeup_url' => 'http://akikoowada.com/',
					'hair' => 'Neil Grupp',
					'hair_url' => 'http://neilgrupp.com/',
					'cover_photo' => 'images/10Jake_Jones_Test/jakejones-02.jpg'
			),
			array(
					'slug' => 'i-D-Magazine-2',
					'name' => 'i-D Magazine',
					'client' => 'i-D Magazine',
					'client_url' => 'http://i-d.vice.com/en_gb/',
					'director' => '',
					'director_url' => '',
					'photographer' => 'Jai Odell',
					'photographer_url' => 'http://www.jaiodell.com',
					'stylist' => 'Katelyn Gray',
					'stylist_url' => 'http://instagram.com/katelynjgray',
					'talent' => 'Kremi',
					'talent_agency' => 'Supreme',
					'talent_url' => 'http://www.suprememanagement.com/Models/2512/KREMI',
					'makeup' => 'Kanako Takase',
					'makeup_url' => 'http://models.com/people/kanako-takase',
					'hair' => 'Ryan Mitchell',
					'hair_url' => '',
					'cover_photo' => 'images/11i-D_Magazine_Editorial/id-01.jpg'
			),
			array(
					'slug' => 'Kim-Haller',
					'name' => 'Kim Haller',
					'client' => 'Kim Haller Collection',
					'client_url' => 'http://www.kim-haller.com',
					'director' => '',
					'director_url' => '',
					'photographer' => 'Paola Ambrosi de Magistris + Murray Hall',
					'photographer_url' => 'http://www.pamu.com/',
					'stylist' => 'Angelica Nelson',
					'stylist_url' => 'http://www.inartistmanagement.com/STYLIST/ANGELICA--Nelson/1/',
					'talent' => '',
					'talent_agency' => '',
					'talent_url' => '',
					'makeup' => 'Yinna Wang',
					'makeup_url' => 'http://www.dripbook.com/yinnawang/',
					'hair' => 'Tony Kelley',
					'hair_url' => 'http://www.tonykelleyhair.com/',
					'cover_photo' => 'images/12Kim_Haller/kimhaller-04.jpg'
			),
			array(
					'slug' => 'Vogue-Australia',
					'name' => 'Vogue Australia',
					'client' => 'Vogue Australia',
					'client_url' => 'http://www.vogue.com.au/',
					'director' => '',
					'director_url' => '',
					'photographer' => 'Jai Odell',
					'photographer_url' => 'http://www.jaiodell.com',
					'stylist' => 'Jessica dos Remedios',
					'stylist_url' => 'http://jessicadosremedios.com/',
					'talent' => 'Elisaveta + Vera',
					'talent_agency' => 'Parts Models LLC',
					'talent_url' => '',
					'makeup' => 'Susie Sobol',
					'makeup_url' => 'http://www.susiesobol.com/',
					'hair' => '',
					'hair_url' => '',
					'cover_photo' => 'images/13Vogue_Australia/vogueaustralia-thumbnail.jpg'
			),
			array(
					'slug' => 'Club-Monaco',
					'name' => 'Club Monaco',
					'client' => 'Club Monaco',
					'client_url' => 'http://www.clubmonaco.com/',
					'director' => '',
					'director_url' => '',
					'photographer' => 'Jai Odell',
					'photographer_url' => 'http://www.jaiodell.com',
					'stylist' => 'Aleksandra Woroneicka',
					'stylist_url' => 'http://www.managementartists.com/stylists/aleksandra-woroniecka',
					'talent' => 'Luca Gadjus',
					'talent_agency' => '',
					'talent_url' => 'http://models.com/models/luca-gadjus  ',
					'makeup' => 'Morgane Martini',
					'makeup_url' => 'http://www.artlistparis.com/make-up/morgane-martini',
					'hair' => 'Shin Arima',
					'hair_url' => 'http://www.frankreps.com/hair/shin-arima/print#/hair/shin-arima/print/51892bff-84f0-4f3e-8267-472a0aa613db',
					'cover_photo' => 'images/14Club_Monaco_September/clubmonacoseptember-01.jpg'
			),
			array(
					'slug' => 'Interview-Magazine',
					'name' => 'Interview Magazine',
					'client' => 'Interview Magazine',
					'client_url' => 'http://www.interviewmagazine.com/',
					'director' => '',
					'director_url' => '',
					'photographer' => 'Jai Odell',
					'photographer_url' => 'http://www.jaiodell.com',
					'stylist' => 'Michelle Cameron',
					'stylist_url' => 'http://www.frankreps.com/stylists/michelle-cameron/print#/stylists/michelle-cameron/print/50351f45-4ea8-4f58-bf1e-70810a0b0910',
					'talent' => 'Bill Hader',
					'talent_agency' => '',
					'talent_url' => 'http://www.imdb.com/name/nm0352778/',
					'makeup' => 'Susie Sobol',
					'makeup_url' => 'http://www.susiesobol.com/',
					'hair' => 'Joey George',
					'hair_url' => 'http://joeygeorge.4ormat.com/',
					'cover_photo' => 'images/15interview_magazine_Bill_Hader/interview-bilhader-01.jpg'
			),
			array(
					'slug' => 'Burdzinski_jimon',
					'name' => 'Burdzinski Jimon',
					'client' => 'Burdzinski Jimon',
					'client_url' => '',
					'director' => '',
					'director_url' => '',
					'photographer' => '',
					'photographer_url' => '',
					'stylist' => '',
					'stylist_url' => '',
					'talent' => '',
					'talent_agency' => '',
					'talent_url' => '',
					'makeup' => '',
					'makeup_url' => '',
					'hair' => '',
					'hair_url' => '',
					'cover_photo' => 'images/16Burdzinski_jimon/burdzinskijimon-01.jpg'
			),
			array(
					'slug' => 'AF-Personal',
					'name' => 'AF Personal',
					'client' => 'AF Personal',
					'client_url' => '',
					'director' => '',
					'director_url' => '',
					'photographer' => '',
					'photographer_url' => '',
					'stylist' => '',
					'stylist_url' => '',
					'talent' => '',
					'talent_agency' => '',
					'talent_url' => '',
					'makeup' => '',
					'makeup_url' => '',
					'hair' => '',
					'hair_url' => '',
					'cover_photo' => 'images/17AF_PERSONAL_FINALS/afpersonal-04.jpg'
			),
			array(
					'slug' => 'Out-Magazine',
					'name' => 'Out Magazine',
					'client' => 'Out Magazine',
					'client_url' => 'http://www.outmagazine.com/',
					'director' => '',
					'director_url' => '',
					'photographer' => 'BJARNE JONASSON',
					'photographer_url' => 'http://www.ateliermanagement.com/photographers/bjarne-jonasson/fashion-1',
					'stylist' => 'Mitchell Belk',
					'stylist_url' => 'http://www.mitchellbelk.com',
					'talent' => 'Eilika',
					'talent_agency' => 'Women Model Management',
					'talent_url' => 'http://www.womenmanagement.com',
					'makeup' => 'Akiko Owada',
					'makeup_url' => 'http://akikoowada.com/',
					'hair' => 'Riad Azar',
					'hair_url' => 'http://www.riadazar.com',
					'cover_photo' => 'images/18Out_Mag/outmagazine-01.jpg'
			),
			array(
					'slug' => 'Jake-Jones-FW',
					'name' => 'Jake Jones Fall Winter',
					'client' => 'Jake Jones',
					'client_url' => 'http://www.whoisjakejones.com/',
					'director' => '',
					'director_url' => '',
					'photographer' => 'Jake Jones',
					'photographer_url' => 'http://www.whoisjakejones.com/',
					'stylist' => 'Rika Watanabe',
					'stylist_url' => 'http://www.rikamwatanabe.com',
					'talent' => 'Eilika',
					'talent_agency' => 'Women Model Management',
					'talent_url' => 'www.womenmanagement.com',
					'makeup' => 'Akiko Owada',
					'makeup_url' => 'http://akikoowada.com/',
					'hair' => 'Kiyo Igarashi',
					'hair_url' => 'http://www.kiyoigarashi.com',
					'cover_photo' => 'images/19Jake_Jones_FW/jakejones-fw-02.jpg'
			),
			array(
					'slug' => 'The-Last-Magazine-2',
					'name' => 'The Last Magazine',
					'client' => 'The Last Magazine',
					'client_url' => 'http://thelast-magazine.com/',
					'director' => '',
					'director_url' => '',
					'photographer' => '',
					'photographer_url' => '',
					'stylist' => '',
					'stylist_url' => '',
					'talent' => '',
					'talent_agency' => '',
					'talent_url' => '',
					'makeup' => '',
					'makeup_url' => '',
					'hair' => '',
					'hair_url' => '',
					'cover_photo' => 'images/20The-Last-Mag/last-magazine-01.jpg'
			),

// Publication: Grey Magazine
// Fashion Editor: Concetta D’Angelo
// Manicurist: Jin Soon Choi @ Jed Root

			array(
					'slug' => 'Jonathan-Cohen-FW-2014',
					'name' => 'Jonathan Cohen FW 2014',
					'client' => 'Jonathan Cohen Studio',
					'client_url' => 'http://jonathancohenstudio.com/',
					'director' => '',
					'director_url' => '',
					'photographer' => '',
					'photographer_url' => '',
					'stylist' => '',
					'stylist_url' => '',
					'talent' => '',
					'talent_agency' => '',
					'talent_url' => '',
					'makeup' => '',
					'makeup_url' => '',
					'hair' => '',
					'hair_url' => '',
					'cover_photo' => 'images/21Jonathan-Cohen-FW-2014/thumb.jpg'
			),
			array(
					'slug' => 'Grey-Magazine',
					'name' => 'Grey Magazine',
					'client' => 'Grey Magazine',
					'client_url' => 'http://grey-magazine.com',
					'director' => '',
					'director_url' => '',
					'photographer' => 'Spencer Ostrander',
					'photographer_url' => '',
					'stylist' => '',
					'stylist_url' => '',
					'talent' => 'Tali Lennox',
					'talent_agency' => '',
					'talent_url' => '',
					'makeup' => 'Stefanie Willmann',
					'makeup_url' => 'http://www.seemanagement.com/artists/stefaniewillmann/',
					'hair' => 'Adam Markarian',
					'hair_url' => 'http://bryanbantry.com',
					'cover_photo' => 'images/22Grey-Magazine/thumb.jpg'
			),
			array(
					'slug' => 'Creem-Magazine',
					'name' => 'Creem Magazine',
					'client' => 'Creem Magazine',
					'client_url' => 'http://creemmag.com',
					'director' => '',
					'director_url' => '',
					'photographer' => 'Barrett Sweger',
					'photographer_url' => 'http://www.barrettsweger.com',
					'stylist' => 'Lana Lackey',
					'stylist_url' => 'http://www.lanajaylackey.com',
					'talent' => '',
					'talent_agency' => '',
					'talent_url' => '',
					'makeup' => '',
					'makeup_url' => '',
					'hair' => '',
					'hair_url' => '',
					'cover_photo' => 'images/23CREEM-MAGAZINE/thumb.jpg'
			)
			,
			array(
					'slug' => 'Club-Monaco',
					'name' => 'Club Monaco',
					'client' => 'Club Monaco',
					'client_url' => 'http://www.clubmonaco.com',
					'director' => '',
					'director_url' => '',
					'photographer' => 'Jai Odell',
					'photographer_url' => 'http://www.jaiodell.com',
					'stylist' => 'Lana Lackey',
					'stylist_url' => '',
					'talent' => 'Ji Hye Park + Vincent LaCrocq',
					'talent_agency' => '',
					'talent_url' => '',
					'makeup' => 'Georgi Sandev',
					'makeup_url' => 'http://georgisandev.com/index2.php',
					'hair' => 'Marki Shkreli',
					'hair_url' => 'http://www.markishkreli.com',
					'cover_photo' => 'images/24Club-Monaco-Party-Shop/thumb.jpg'
			),
			array(
					'slug' => 'barneys',
					'name' => "BARNEY'S New York",
					'client' => "BARNEY'S New York",
					'client_url' => 'http://www.barneys.com',
					'director' => '',
					'director_url' => '',
					'photographer' => 'Jai Odell',
					'photographer_url' => 'http://www.jaiodell.com',
					'stylist' => 'Andrew Dochen',
					'stylist_url' => '',
					'talent' => 'Karolin W',
					'talent_agency' => 'http://www.nextmanagement.com',
					'talent_url' => '',
					'makeup' => 'Emi Kaneko',
					'makeup_url' => 'http://www.emikaneko.com/',
					'hair' => 'Takuya Sugawara',
					'hair_url' => 'http://www.takuyasugawara.com',
					'cover_photo' => 'images/25Barneys/thumb.jpg'
			),
			array(
					'slug' => 'Club-Monaco-Collection',
					'name' => "Club Monaco",
					'client' => "Club Monaco",
					'client_url' => 'http://www.clubmonaco.com',
					'director' => '',
					'director_url' => '',
					'photographer' => 'Jai Odell',
					'photographer_url' => 'http://www.jaiodell.com',
					'stylist' => 'Andrew Dochen',
					'stylist_url' => '',
					'talent' => 'Luca Gadjus',
					'talent_agency' => 'http://www.imgmodels.com',
					'talent_url' => '',
					'makeup' => 'Morgane Martini',
					'makeup_url' => 'http://models.com/people/morgane-martini',
					'hair' => 'Shin Arima',
					'hair_url' => '',
					'cover_photo' => 'images/26Club-Monaco-Collection/thumb.jpg'
			)



		);

		
		DB::table('setdesign')->insert($array);
	}

}